# Generated by Django 4.2.2 on 2023-06-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avataar/'),
        ),
    ]
