# Generated by Django 4.2.2 on 2023-06-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_avatar_img_account_avatar'),
        ('cart', '0002_cart_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.account', verbose_name='Покупатель'),
        ),
    ]
