name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/backend/requirements.txt
      - name: Run Tests
        run: |
          cd project
          cd backend
          python manage.py test
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401"
          max-line-length: "120"
          path: "./project/backend"
